spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/demoproject
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml


server:
  port: 8585
  servlet:
    context-path: /api/
